name: Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      fail-fast: true
      matrix:
        config:
          - preset: android-x64
            ndk_version: 26.3.11579264
          - preset: android-arm
            ndk_version: 26.3.11579264
          - preset: android-arm64
            ndk_version: 26.3.11579264
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install System Packages
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake ninja-build
      - name: Setup vcpkg
        working-directory: /opt
        run: |
          rm -rf vcpkg
          git clone --single-branch --filter=blob:none https://github.com/Microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg integrate install
          ./vcpkg/vcpkg --version
          test -d /opt/vcpkg-binary-cache || mkdir /opt/vcpkg-binary-cache

      - name: Cache Vcpkg Dependencies
        uses: actions/cache@v3
        with:
          key: ${{matrix.config.preset}}-${{hashFiles('vcpkg.json')}}
          path: /opt/vcpkg-binary-cache


      - uses: actions/setup-java@v1
        with:
          java-version: "11.x"

      - name: Configure NDK
        env:
          ANDROID_ROOT: /usr/local/lib/android
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        run: |
          echo "y" | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "ndk;${{matrix.config.ndk_version}}"

      - name: Configure
        env:
          VCPKG_ROOT: /opt/vcpkg
          VCPKG_DEFAULT_BINARY_CACHE: /opt/vcpkg-binary-cache
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/${{matrix.config.ndk_version}}
        run: cmake -S . --preset ${{matrix.config.preset}}

      - name: Build Debug
        run: |
          cmake --build --preset ${{matrix.config.preset}} --config Debug

      - name: Build Release
        run: |
          cmake --build --preset ${{matrix.config.preset}} --config Release
